[package]
name = "earldb"
version = "0.1.0"
authors = ["Past9 <past9sys@gmail.com>"]

[profile.test]
debug = true

[dependencies]
byteorder = "0.5.3"

[dependencies.uuid]
version = "0.2.2"
features = ["v4"]
